services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    restart: unless-stopped
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./runtime/keycloak/realm-mediamtx.json:/opt/keycloak/data/import/realm-mediamtx.json:ro

  mediamtx:
    image: bluenviron/mediamtx:1.15.4
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"      # RTSP
      - "8888:8888"      # HLS fallback
      - "8889:8889"      # WebRTC
      - "8189:8189/udp"  # ICE / WebRTC UDP
      - "8189:8189/tcp"  # ICE / WebRTC TCP fallback
      - "9997:9997"      # API MediaMTX
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    depends_on:
      - keycloak

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: stream-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - mediamtx
    env_file:
      - ./.env
    environment:
      # Container-to-container DNS for Docker network.
      MEDIAMTX_HOST: mediamtx
      MEDIAMTX_API: http://mediamtx:9997
      KEYCLOAK_BASE_URL: http://keycloak:8080
