services:
  mediamtx:
    image: bluenviron/mediamtx:1.15.4
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"      # RTSP
      - "8888:8888"      # HLS fallback
      - "8889:8889"      # WebRTC
      - "8189:8189/udp"  # ICE / WebRTC UDP
      - "8189:8189/tcp"  # ICE / WebRTC TCP fallback
      - "9997:9997"      # API MediaMTX
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: stream-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mediamtx
    env_file:
      - ./.env
